### PR TITLE
Fix precompilation on x86

### LINKED ISSUE #43: Support x86?
Hello! One of the CI runs for a project I'm working on uses Julia built for x86, where the default integer type is `Int32`. It failed to precompile GeometricalPredicates with the following error:

```
ERROR: LoadError: MethodError: no method matching quadrants(::Int32, ::Int32, ::Int32, ::Int32)
Stacktrace:
 [1] _init_inv_peano_3d()
   @ GeometricalPredicates ~/.julia/packages/GeometricalPredicates/1dBKW/src/GeometricalPredicates.jl:998
```

Why this happens is pretty clear in the source:

https://github.com/JuliaGeometry/GeometricalPredicates.jl/blob/045d35599a06c45c603b67fabcb970113c342108/src/GeometricalPredicates.jl#L993-L1006

and could be fixed by just adding type annotations for `rotation::Int64`, `bitx::Int64`, etc..

I don't know if x86 is something you want to support? But if not, could you maybe add a line about that in the readme, or get the precompile to fail with a more meaningful message?

I'm also happy to contribute a PR if that would be helpful.

Thanks!

### PR DESCRIPTION
**Pull request by blegat**
For 64-bit, `Int` and `Int64` are the same so it won't change the behavior for 64-bit.
For 32-bit, it was not precompiling before and it is now so that's an improvement.

I don't expect tests will pass for 32-bit but having it precompile is a first step.

Closes https://github.com/JuliaGeometry/GeometricalPredicates.jl/issues/43

### CODE REVIEW

File: src/GeometricalPredicates.jl [hunk 1]
```diff
@@ -941,7 +941,7 @@ const quadrants_arr = [
   3, 4, 0, 7, 2, 5, 1, 6,
   4, 5, 7, 6, 3, 2, 0, 1,
   5, 2, 6, 1, 4, 3, 7, 0]
-quadrants(a::Int64, b::Int64, c::Int64, d::Int64) = (@inbounds x = quadrants_arr[1+a<<3+b<<2+c<<1+d]; x)
+quadrants(a::Int, b::Int, c::Int, d::Int) = (@inbounds x = quadrants_arr[1+a<<3+b<<2+c<<1+d]; x)
```
Comment (sjkelly) [inline src/GeometricalPredicates.jl:944]: I am not sure why imposing `Int64` prevents precompilation on x86?

Comment (sjkelly) [reply src/GeometricalPredicates.jl:944]: Okay I see in the linked issue.
